## ライブラリのインポート

In [1]:
import numpy as np

## NumPy配列の作成

In [28]:
# list型から作成
data = [
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11]
]

np.array(data)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
data = np.arange(12).reshape(3, 4)

data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
data.shape

(3, 4)

In [11]:
data.ndim

2

In [12]:
type(data)

numpy.ndarray

## 配列へのアクセス

In [29]:
X = np.array([[41, 57],[12, 21],[1, 8]])

X

array([[41, 57],
       [12, 21],
       [ 1,  8]])

In [30]:
X[0]

array([41, 57])

In [31]:
X[0][1]

57

In [32]:
X[0, 1]

57

In [33]:
for row in X:
  print(row)

[41 57]
[12 21]
[1 8]


## NumPy配列の編集

In [47]:
X = np.array([[41, 57],[12, 21],[1, 8]])

X.shape

(3, 2)

In [48]:
# 2次元を1次元に変更
X = X.flatten()

X

array([41, 57, 12, 21,  1,  8])

In [50]:
X[np.array([1, 3, 5])]

array([57, 21,  8])

In [43]:
# ブーリアンのフィルター
X > 20

array([ True,  True, False,  True, False, False])

In [46]:
# ブーリアンがTrueの要素だけ抽出（ブーリアンのフィルター）
X[X > 20]

array([41, 57, 21])

In [51]:
X

array([41, 57, 12, 21,  1,  8])

In [52]:
X.shape

(6,)

In [53]:
# 2次元を1次元に変更
X[:, np.newaxis]

array([[41],
       [57],
       [12],
       [21],
       [ 1],
       [ 8]])